baseURL = "http://fsan.githubio.com/blog"
languageCode = "en-us"
title = "fsan"
theme = "ezhil"
paginate = 1

copyright = "© 2020"

pygmentsstyle = "monokailight"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses=true

googleAnalytics = "UA-3512812-2"
disqusShortname = "fabiosancinetti"

[params]
	subtitle = "" #"Clean and minimal personal [blog theme for Hugo](https://fsan.github.com/blog)"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "light" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	customJS = ["https://code.jquery.com/jquery-3.4.1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/fsan"

#  [[params.social]]
#  name = "RSS"
#  icon = "rss"
#  url = "/index.xml"

[taxonomies]
   tag = "tags"
